# Generated by Django 4.1.6 on 2023-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
